### ISSUE TITLE
GrannyTextRenderer doesn't size extensions properly

### ISSUE THREAD

**Issue by jbfaden** [das-developers/das2java#11]
The GrannyTextRenderer has a means for allowing custom drawing codes in.  For example, there's an Autoplot example which imports a LaTeX library and uses it to render LaTeX within a string.  This would be a great feature, but unfortunately, the code that calculates the size of the draw region has an issue, I think.  

The Autoplot script is here: https://github.com/autoplot/dev/blob/master/rfe/sf/625/latexPainter.jy

**Comment by jbfaden** [comment]
See the "The" which is clipped.
![2021-05-28T17-42-24](https://user-images.githubusercontent.com/3385225/120048213-1fabdf80-bfdc-11eb-8789-87c2a2170f71.png)

**Comment by cpiker** [comment]
Hey, that looks cool.  Didn't know Autoplot could do that.

**Comment by jbfaden** [comment]
"Das2 can do that," is what you mean... Autoplot gets it for free...

**Comment by jbfaden** [comment]
This is finally fixed, where the wrong font object was passed to the painter when layout is done.
