### ISSUE TITLE
axisOffset property  allows for multiple axes on one plot

### ISSUE THREAD

**Issue by jbfaden** [das-developers/das2java#2]
A few people have asked for a way to offset the dasAxis from the plot, so a Z-stack of plots axes can be used to control parameters.  Right now you can have a left axis and a right axis, but this will allow for any number of parameters and the axis can always be on the left side.

**Comment by VoyagerPWS** [comment]
In a similar vein, it would be nice to have, e.g., a single time axis or multiple shared axes for a vertical stack of plots.

**Comment by jbfaden** [comment]
So this sort of plot is possible:
![20210504_155513](https://user-images.githubusercontent.com/3385225/117032632-41f55a80-acc7-11eb-8d37-261340273c94.png)

There's still work that needs to be done to handle events properly.

**Comment by jbfaden** [comment]
VoyagerPWS=Larry, right?  This can be done already by creating a big non-visible plot and binding the axes together with beans bindings, or in Das2 you could just create an axis object by itself and bind to that.

**Comment by jbfaden** [comment]
You can do some pretty silly things.  Is this what you mean:
![20210504_160556](https://user-images.githubusercontent.com/3385225/117034291-c3012180-acc8-11eb-98c4-e9a3c139806e.png)
