### ISSUE TITLE
issues with scan next/prev

### ISSUE THREAD

**Issue by jbfaden** [das-developers/das2java#39]
The DasAxis should provide a "scan next" button when the "step next" action would advance to a frame with no data.  This feature has a few problems:

* "scan" action doesn't show initially, must step first
* scanning to the next frame steps an integer number of times, when it would be more appropriate to recenter.
* sometimes the "scan" or "step" button doesn't appear, though clicking there would take the action.

**Comment by jbfaden** [comment]
scanning to the next frame recenters now.

**Comment by cpiker** [comment]
How do you decide how far to scan?

**Comment by jbfaden** [comment]
It must have the data in memory, which is a place where things could be improved.  So it uses the paradigm that the scientist loads all the data, then zooms in to the first interval, and scans from there.  I'm not sure how it would be improved to load more data, since it would have to be aware of the source of the data, which it is not.

**Comment by jbfaden** [comment]
Actually, it's Autoplot which adds the "scan" action, I was letting Netbeans find things for me and didn't notice this is actually not a Das2 thing.  So it could probably be much smarter, allowing scans outside of the loaded data.

**Comment by jbfaden** [comment]
See also https://sourceforge.net/p/autoplot/bugs/1209/ a related bug in the Autoplot bug tracker.

**Comment by jbfaden** [comment]
I found a nice case to study this, but since it's an Autoplot bug, I'll describe the case there and close this ticket. (https://sourceforge.net/p/autoplot/bugs/1209/)

**Comment by jbfaden** [comment]
Actually this is the Autoplot ticket: https://sourceforge.net/p/autoplot/bugs/1359/
