### ISSUE TITLE
Maybe tweak how vertical space is computed for OutsideNE legends in DasPlot

### ISSUE THREAD

**Issue by DiamondJim87** [das-developers/das2java#66]
In DasPlot.java around line 476 is a block for computing the space necessary for legends for the case "OutsideNE". The vertical space is set as follows:
<pre>
               mrect.y= yAxis.getRow().getDMinimum(); // em/5 determined by experiment.
</pre>

I am finding that the tops of larger letters, like capital C, are slightly cut off with this rectangle size. Just to confirm this is the source of my problem, I added 5 pixels to this vertical extent, and voila, the letters look fine.

Is there a different way to set this spacing, perhaps somehow based on font metrics?

**Comment by jbfaden** [comment]
My recollection is this needs to be studied on many different platforms.  Many of the fonts seem to have incorrect metrics.  I don't see what I was referring to with "em/5", but the way, do you?  Clearly the top of the legend should be the top of the GrannyTextRenderer, so it's probably the GrannyTextRenderer which needs tweaking.  

Could you post screenshots, and id the platform (Java version too)?

**Comment by DiamondJim87** [comment]
Thanks for the rapid response!

Java version is 1.8. I'm running on a Mac. These are Larry's "StatusLineRenderer" plots, where the only significant axis is the X axis. The Y is just 0 to 1 and we suppress the axis and color it just to show whether there are data in that time range (red) or not (white).

The idea of emsize / 5 doesn't make sense to me either. Maybe it was something different and when the code got changed the comment didn't?

Here's a screen shot:

<img width="1276" alt="Screenshot 2023-07-24 at 6 06 00 PM" src="https://github.com/das-developers/das2java/assets/17085823/66fe551c-ce7d-435d-a70a-882eaeff542c">

**Comment by jbfaden** [comment]
They definitely look a little high to me.  The goal is to line up top of an M or T with the DasRow top.  I do remember experimenting a lot here, so much that I have no idea what the final solution was.  Another thought would be to have a legendLabel position which is OutsideSE, since it's very easy to know the baseline for a font.  I think I'll look into this now, and I'll let you know what I find out.

**Comment by jbfaden** [comment]
You can see here how the title ends up low on Linux: 
![image](https://github.com/das-developers/das2java/assets/3385225/80df5d53-f947-45fa-b589-4faecf3d912f)

**Comment by jbfaden** [comment]
And those are legend labels, not annotations, right?  You must have found my kludge which lets you turn off the symbol drawing, right?  Note with annotations you would have a lot more control, but it would also be quite a bit more code.  Do you add things in a loop?

**Comment by DiamondJim87** [comment]
Yes, legend labels, not annotations. Yes, it's in a loop, the number of plots on any given canvas is arbitrary.

**Comment by jbfaden** [comment]
I think the best solution is for me to add OutsideSE to the legendPosition property.

**Comment by DiamondJim87** [comment]
That probably would do the trick for this case.

**Comment by jbfaden** [comment]
Give it a pull and let me know how that looks.  On Linux it's actually 1-2 pixels too high, and I need to set the bounding box since there may be a descender (y or p).

**Comment by DiamondJim87** [comment]
Ah, much better. Thanks again, this meets my needs perfectly!
<img width="1257" alt="Screenshot 2023-07-24 at 9 42 18 PM" src="https://github.com/das-developers/das2java/assets/17085823/3461eb02-0692-46f4-9383-4e674ccee160">

**Comment by jbfaden** [comment]
I need to play with this on a mac.  It still draws 4-5 pixels too high with this font, even though it's not clipping now.  I'm going to reopen the ticket, just so I remember to look at this on different platforms.

**Comment by jbfaden** [comment]
- [ ] I just noticed the OutsideSE legend position doesn't account for multi-line legends.

**Comment by jbfaden** [comment]
I've added a .vap which demos the problem where multi-line legend is incorrectly positioned.  See https://github.com/autoplot/dev/blob/master/bugs/ghdas2/0066/demoBug.vap

**Comment by jbfaden** [comment]
Multi-line, outsideSE legends are fixed.
