### ISSUE TITLE
DasAxis titles are not positioned properly if tick labels occupy more than one line

### ISSUE THREAD

**Issue by DiamondJim87** [das-developers/das2java#78]
This follows on from issue #77. The space seems to be computed correctly, but the title position does not account for the taller labels. For example, if using a time axis, try the format string "%y-%j!c%H:%M" (note the "!c" in the middle of that which splits the date/time onto two lines). The result should look something like the attached screen shot.
<img width="1160" alt="Screenshot 2023-08-22 at 10 43 11 AM" src="https://github.com/das-developers/das2java/assets/17085823/bbbcc152-a2ea-4310-852c-650fe9a26b21">

**Comment by jbfaden** [comment]
Indeed...  Usually we have the first tick with the date, and this is why the bug remains.  The code should look for the format property and shift down the title if necessary.

**Comment by jbfaden** [comment]
This is corrected, so now if the format property is set then "blLabelRect" is used to recalculate the offset needed.

![image](https://github.com/das-developers/das2java/assets/3385225/f573f06d-4be5-4bc7-b20c-b967cc382ba8)
